---
#----------------------------------
# Application Environment Setting
#----------------------------------
build:
  environments:
    - local
    - feature
    - dev
    - prod
#----------------------------------
# Application Setting
#----------------------------------
# cSpell:ignore ibatis typehandler millis hiddenmethod datasource dbcp evictable jdbc fasterxml databind
server:
  shutdown: graceful
  address:
    __ENVIRONMENT__:
      default: 0.0.0.0
      local: 127.0.0.1
  servlet:
    context-path:
      __ENVIRONMENT__:
        default: /
    encoding:
      force: true

#----------------------------------
#  Cross-Origin Resource Sharing (CORS) Setting
#----------------------------------
cors:
  access-control-allow-origin:
    allow-all:
      __ENVIRONMENT__:
        default: false
        local: true
#----------------------------------
# Deemed Date Setting
#----------------------------------
# みなし日使用フラグ
# Y: 使用、N: 未使用
deemed:
  date:
    use:
      flag:
        __ENVIRONMENT__:
          default: Y
          prod: N
#----------------------------------
# Debug Setting
#----------------------------------
# trueだとログレベルがINFO以上でもisDebugEnabled()判定されたデバッグログは出力される
debug:
  __ENVIRONMENT__:
    default: false
    local: true
#----------------------------------
# Logging Settings
#----------------------------------
log:
  aspect:
    limited-log-length: 512 #@LimitAopLogの上限となる文字列の長さのデフォルト値
  http-request:
    payload:
      __ENVIRONMENT__:
        default: false
        local: true
  file:
    path:
      __ENVIRONMENT__:
        default: logs/app-api
    extension: .log
    max:
      history: 7

logging:
  detailed:
    packages: com.accenture.acts,com.skeleton
  level:
    root:
      __ENVIRONMENT__:
        default: DEBUG
        prod: INFO
    com.accenture:
      __ENVIRONMENT__:
        default: DEBUG
        prod: INFO
    # HealthCheckのログを出力すると膨大な量になるため基本は出さない
    com.accenture.acts.controller.HealthCheckController:
      __ENVIRONMENT__:
        default: ERROR
        local: DEBUG
    com.accenture.acts.controller.DatabaseHealthCheckController:
      __ENVIRONMENT__:
        default: ERROR
        local: DEBUG
    com.accenture.acts.service.impl.DatabaseHealthCheckServiceImpl:
      __ENVIRONMENT__:
        default: ERROR
        local: DEBUG
    # 3rd party Loggers
    org.springframework:
      __ENVIRONMENT__:
        default: DEBUG
        prod: INFO
    org.apache.http.wire:
      __ENVIRONMENT__:
        default: INFO
        local: DEBUG

#----------------------------------
# MyBatis Setting
#----------------------------------
mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-aliases-package: com.accenture.acts.entity,com.skeleton.entity
  type-handlers-package: com.accenture.acts.mybatis.typehandler

#----------------------------------
# Spring Setting
#----------------------------------
spring:
  lifecycle:
    # Graceful shutdownの停止までの猶予期間。デフォルトは30s。
    timeout-per-shutdown-phase: 60s
  # 組み込みhttpサーバを起動せずgRPCサーバのみとして利用する場合、spring.main.web-application-type=noneを設定する。
  # httpサーバとして利用する場合はコメントアウトする。
  #  main:
  #    web-application-type: none
  aop:
    proxy-target-class: true
  datasource:
    continue-on-error: false
    dbcp2:
      default-auto-commit: false
      initial-size: 1
      max-idle: 50
      max-total: 100
      max-wait-millis: 10000
      min-evictable-idle-time-millis: 600000 # 10 min
      min-idle: 0
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 30000 # 30 sec
      validation-query: SELECT 1
    driverClassName: org.postgresql.Driver
    password:
      __ENVIRONMENT__:
        default: P@ssw0rd
        dev: P@ssw0rd
        ita: P@ssw0rd
    type: org.apache.commons.dbcp2.BasicDataSource
    url:
      __ENVIRONMENT__:
        # cSpell:disable
        default: "jdbc:postgresql://localhost:5432/actsdb"
        dev: "jdbc:postgresql://localhost:5432/actsdb"
        ita: "jdbc:postgresql://localhost:5432/actsdb"
        # cSpell:enable
    username:
      __ENVIRONMENT__:
        default: acts
        dev: acts
        ita: acts
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  mvc:
    hiddenmethod:
      filter:
        enabled: false
  http:
    encoding:
      enabled: false
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

#----------------------------------
# Version Info Setting
#----------------------------------
version:
  endpoint:
    enabled:
      __ENVIRONMENT__:
        default: true
    url: "/version"
  file:
    path: "classpath:www/version.json"
#----------------------------------
# Health Check Setting
#----------------------------------
health-check:
  endpoint:
    enabled:
      __ENVIRONMENT__:
        default: true
    url: "/health-check/ping"
health-check-db:
  endpoint:
    enabled:
      __ENVIRONMENT__:
        default: true
    url: "/health-check/ping-db"

#----------------------------------
# Retry Settings
#----------------------------------
recoverable-data-access:
  retry:
    enabled: false

# ----------------------------------
# Multiple Data Source Settings
# ----------------------------------
# 複数のDataSourceを利用する場合はspring.datasource配下の設定を削除し、以下の設定を追加する。
# datasource:
#   read-write:
#     continue-on-error: false
#     driverClassName: org.postgresql.Driver
#     password:
#       __ENVIRONMENT__:
#         default: P@ssw0rd
#         dev: P@ssw0rd
#         ita: P@ssw0rd
#     type: org.springframework.jdbc.datasource.SimpleDriverDataSource
#     url:
#       __ENVIRONMENT__:
#         # cSpell:disable
#         default: "jdbc:mysql://localhost:3306/actsdb?useSSL=false&zeroDateTimeBehavior=convertToNull&connectionTimeZone=SERVER"
#         dev: "jdbc:mysql://localhost:3306/actsdb?verifyServerCertificate=false&useSSL=true&requireSSL=true&zeroDateTimeBehavior=convertToNull&connectionTimeZone=SERVER"
#         ita: "jdbc:mysql://localhost:3306/actsdb?verifyServerCertificate=false&useSSL=true&requireSSL=true&zeroDateTimeBehavior=convertToNull&connectionTimeZone=SERVER"
#         # cSpell:enable
#     username:
#       __ENVIRONMENT__:
#         default: acts
#         dev: acts
#         ita: acts
#   read-only:
#     continue-on-error: false
#     driverClassName: org.postgresql.Driver
#     password:
#       __ENVIRONMENT__:
#         default: P@ssw0rd
#         dev: P@ssw0rd
#         ita: P@ssw0rd
#     type: org.springframework.jdbc.datasource.SimpleDriverDataSource
#     url:
#       __ENVIRONMENT__:
#         # cSpell:disable
#         default: "jdbc:mysql://localhost:3306/actsdb?useSSL=false&zeroDateTimeBehavior=convertToNull&connectionTimeZone=SERVER"
#         dev: "jdbc:mysql://localhost:3306/actsdb?verifyServerCertificate=false&useSSL=true&requireSSL=true&zeroDateTimeBehavior=convertToNull&connectionTimeZone=SERVER"
#         ita: "jdbc:mysql://localhost:3306/actsdb?verifyServerCertificate=false&useSSL=true&requireSSL=true&zeroDateTimeBehavior=convertToNull&connectionTimeZone=SERVER"
#         # cSpell:enable
#     username:
#       __ENVIRONMENT__:
#         default: acts
#         dev: acts
#         ita: acts
